server {
    listen 80 default_server;

    root /usr/share/nginx/html;
    index index.html;

    # Serve index.html for any 503 error
    error_page 503 /index.html;

    location / {
        return 503;
    }

    location = /index.html {
        internal;
    }

    add_header Retry-After 3600 always;
}