server.document-root = "/app/serve"
server.port = 8080
server.username = "static"
server.groupname = "static"
index-file.names = ( "index.html" )
mimetype.assign = (
    ".html" => "text/html",
    ".txt" => "text/plain",
    ".jpg" => "image/jpeg",
    ".jpeg" => "image/jpeg",
    ".png" => "image/png",
    ".gif" => "image/gif",
    ".svg" => "image/svg+xml"
)