server.document-root = "/static"
server.port = 8080
server.username = "busybox"
server.groupname = "busybox"
index-file.names = ( "index.html" )
mimetype.assign = ( ".html" => "text/html", ".txt" => "text/plain" )