worker_processes 1;  # global context, 1 worker is enough for a maintenance page

events {
    worker_connections 1024;  # number of connections per worker
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    # Include your server configs
    include /etc/nginx/conf.d/*.conf;
}